[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "concopt"
authors = [
    {name = "Tom Marshall", email = "qwertytam@gmail.com"},
]
description = "Optimize Concorde flight operations"
readme = "README.rst"
requires-python = ">=3.11"
keywords = ["concorde", "flight"]
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "numpy",
    "pandas",
    "pint",
    "pint-pandas",
    "requests",
    "scipy"
]

version = "0.0.1"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
concopt = ["data/*.csv"]