[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "concopt"
authors = [
    {name = "Tom Marshall", email = "qwertytam@gmail.com"},
]
description = "Optimize Concorde flight operations"
readme = "README.rst"
requires-python = ">=3.11"
keywords = ["concorde", "flight"]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "cdsapi",
    "dask",
    "matplotlib",
    "netCDF4",
    "numpy",
    "pandas",
    "pint",
    "pint-pandas",
    "requests",
    "scipy",
    "SimConnect",
    "xarray"
]

version = "0.0.1"

[project.optional-dependencies]
test = ["pytest", "ipykernel"]

[project.scripts]
concopt = "concopt.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]